### PR TITLE
Adding unit tests, deprecating old tests

### PR DESCRIPTION
**Pull request by Trudeaucj**

### CODE REVIEW

**Comment by howarddierking** [comment]
what's the story with all of the commented out files?

**Comment by Trudeaucj** [comment]
Incase you wanted examples, no need to keep them around if you don't want them.

**Comment by bdmesh** [comment]
For the test files that are still in the main test dir, the pattern seems to be tests for all the GET method, but commented out sections for POST, PUT, and DELETE tests.   I see that the code behind them has at least a couple of these functions actually implemented, so are the commented sections in the tests just to indicate that we need to test these other functions as well?  Did you just run out of time?

**Comment by Trudeaucj** [comment]
Yes that I ran out of time and tests need to be written for the others as well.

**Pull request merged**
